New viewport cases
luxteam/jobs_test_inventor pull request #157
Opened 2022-04-19 19:30 UTC by Sofshik

2022-04-20 07:18 UTC, Speedwag00n requested changes
Нужен билд с новыми кейсами, чтобы посмотреть, как все работает с разными карточками

2022-04-20 07:18 UTC, Speedwag00n commented on jobs/Tests/Viewport/test_cases.json
> +        "status": "skipped",
Почему этот кейс скипнут?

2022-04-20 07:18 UTC, Speedwag00n commented on jobs/Scripts/extensions/Viewport.py
> +def open_usdviewer_console(args, case, current_try, screens_path, extension = ".usd"):
Выглядит, как лишняя функция

2022-04-20 08:21 UTC, Sofshik commented on jobs/Scripts/extensions/Viewport.py
> +def open_usdviewer_console(args, case, current_try, screens_path, extension = ".usd"):
Всё поправила

2022-05-27 06:34 UTC, Speedwag00n approved these changes

2022-06-13 16:59 UTC, closed without merging