Standalone RPRViewer tests
luxteam/jobs_test_inventor pull request #32
Opened 2021-06-28 10:47 UTC by NISHIY-EKSDEE

## JIRA TICKET
https://adc.luxoft.com/jira/browse/STVCIS-2360
## PURPOSE
Unite Inventor and standalone RPRViewer tests due to very similar logic and code
## EFFECT OF CHANGE
New toolname parameter in run.bat and build_usd_cache.bat scripts
Feature to skip cases for each tool separately using `tools` field in test_cases
## NOTES FOR REVIEWERS
For RPRViewer after copying test cases, every INV prefix replaces with USDPL. Reports, images, json files will contain these updated names as well.
Exported scene won't contain InventorViewportCamera -> images will have different angle. In Material_Library since we click on a specific element, the coordinates will also change
## RELATED PR'S

## REPORTS
[Build with Inventor toolname argument](https://rpr.cis.luxoft.com/job/RadeonProUSDViewerManual/475/)
[Build with RPRViewer toolname argument](https://rpr.cis.luxoft.com/job/RadeonProUSDViewerManual/479/)

2021-07-04 08:24 UTC, Speedwag00n reviewed
По тем отчетам, что прикреплены, замечаний нет
Но нужно в любом случае сделать фулл прогоны
Стоит обратить внимание на 004 и 005 кейсы. Их можно сразу скипнуть для RPRViewer, т.к. они не имеют без Инвентора смысла (там проверяется экспорт сцены в usd/usda и ее открытие через RPRViewer напрямую)

2021-07-04 08:24 UTC, Speedwag00n commented on jobs/Scripts/simpleRender.py
> +        if args.is_inventor:
Можно сделать отдельный метод в utils для определения, скипнут кейс или нет. Вот пример из Майи:
https://github.com/luxteam/jobs_test_maya/blob/master/jobs/Scripts/utils.py#L1

2021-07-04 08:24 UTC, Speedwag00n commented on scripts/build_usd_cache.py
> +                print("Inventor window found. Wait a bit")
Можно вынести код этого блока else в отдельные функции в этом же файле, как сделано с find_usd_viewer_window и viewer_render

2021-07-05 16:58 UTC, NISHIY-EKSDEE commented on jobs/Scripts/simpleRender.py
> +        if args.is_inventor:
Вынес в is_case_skipped, оставил только переименование кейсов для RPRViewer

2021-07-05 16:59 UTC, NISHIY-EKSDEE commented on scripts/build_usd_cache.py
> +                print("Inventor window found. Wait a bit")
Вынес части в open_scene и open_usdviewer

2021-07-05 20:41 UTC, NISHIY-EKSDEE commented
> Стоит обратить внимание на 004 и 005 кейсы. Их можно сразу скипнуть для RPRViewer, т.к. они не имеют без Инвентора смысла (там проверяется экспорт сцены в usd/usda и ее открытие через RPRViewer напрямую)

В Smoke скипнул все кейсы после 003, т.к. они подразумевают взаимодействие с Инвентором (кроме 009, там невозможно кликнуть на элемент сцены из-за другой камеры и ракурса)

2021-08-02 07:00 UTC, Speedwag00n reviewed
Посмотрел последние изменения. С ними все ок
Нужно решить мердж конфликт и посмотреть фулл Инвентора хотя бы на одной карточке с этой веткой и всеми тестами, что сейчас есть

2021-09-07 06:52 UTC, Speedwag00n requested changes
Пара замечаний по автотестам:
- Inventor Appearance рендерится без материалов. По скриншотам материал явно аплаится, скорее всего проблема в устаревшем сабмодуле Вьюера. Нужно это проверить. Для этого можно создать временную ветку в репозитори для Инвентор плагина и там обновить сабмодуль Вьюера до актуальной версии + запустить с ним Inventor Appearance.
- По поводу МатЛибы в standalone Вьюере: ерроры на слабых карточках из-за того, что сцена очень крупная с Perspective камерой и вьюер слишком долго их рендерит. Стоит для stadalone Вьюера отдалять камеру (отдалять, пока размер фигуры не будет примерно таким же, как в плагине для Инвентора). Как итог, должно помочь с еррорами

2021-09-10 06:33 UTC, Speedwag00n approved these changes
Я видел фикс для Матлибы, все ок
Осталось решить с разработчиками проблему с прокидыванием изменений из Инвентора во Вьюер

2021-09-17 14:45 UTC, merged